= Замечания по заданию

== Текст задания

Имеется очередь элементов на обработку.
Каждый элемент имеет собственный идентификатор (itemId) и принадлежит к
некоторой группе (groupId).

Внутри группы элементы должны обрабатываться строго последовательно,
в порядке увеличения идентификаторов элементов. Элементы разных групп
могут обрабатываться параллельно.

Обработка элемента производится путем вызова некоторого метода с
параметрами itemId и groupId, который печатает полученные идентификаторы
элементов. Элементы в очередь добавляются асинхронно внешним процессом.
После обработки элемент должен быть удален из очереди.

Написать обработчик очереди, работающий в несколько потоков.
Максимальное количество потоков ограничено, задается при старте
обработчика и в общем случае меньше числа групп. Обеспечить равномерную
обработку групп элементов: наличие в очереди групп с большим количеством
элементов не должно приводить к длительным задержкам в обработке других
групп.

Приветствуется следование принципам DRY, KISS и YAGNI, а также
использование современных подходов и среды исполнения кода.
Результат залить в GitHub, прислать ссылку.

==  Основные требования:

* Последовательнось обработки элементов в группе в порядке увеличения идентификатора
* Равномерная многопоточная обработка групп элементов
* Работа с очередью наполняемой асинхронно, удаление обработанных элементов

== Некоторые пояснения по выполненному заданию

=== Общее описание очереди и работы с ней

В качестве подобной 'асинхронной очереди' я выбрал обычное HTTP-соединение.
Это дало мне возможность написать как обработчик элементов, так и генератор
тестовых элементов для последующего анализа. Генератор тестовых данных реализован
в классе *cft.sample.app.tester.DataGenerator*. Реализует следующие стратегии
генерации последовательностей тестовых элементов:

[cols="2", options="header"]
|===
|Название
|Описание

|LINEAR
|Элементы принадлежат только одной группе. Нумерация элементов линейная,
по возрастанию.

|RANDOM
|Элементы назначаются случайным образом любой из 10-ти групп. Нумерация
элементов линейная, по возрастанию, сквозная для всех групп.

|MANUAL
|На данный момент не реализована. Предполает генерацию произвольной
последовательности элементов. При использовании будет сгенерировано
исключение *NotImplementedException*.
|===

=== Краткое описание обработки элементов в группе

Требование обработки элементов строго по возрастанию идентификатора реализовано
путем отбрасывания элементов с меньшим идентификатором. Элементы с повторяющимеся
идентификаторами в пределах одной группы не допускаются. Элементы в группе
после такой проверки уже находятся в упорядоченном состоянии.

=== Описание механизмов обработки групп элементов

Реализовано две стратегии обработки групп элементов:

[cols="3", options="header"]
|===
|Название
|Описание
|Метод реализации стратегии

|INADVANCE
|Группы с элементами передаются на обработку (в текущей реализации на печать)
последовательно, одна за другой. В данной стратегии можно предусмотреть
ограничение кол-ва элементов в группе (за это отвечает параметр
*common.queueMaxSize*). При превышении указанного кол-ва новые элементы группы
отбрасываются.
|cft.sample.app.scheduler.workers.WorkerInadvance.work

|SIMPLIFIED_RR
|При обработке групп элементов происходит 'склеивание' содержимого групп с
небольшим кол-ом элементов. Максимальная длина такой 'результирующей' группы
групп определяется параметром *common.rrThreshold*. После подобной 'склейки'
новая результирующая группа отправляется на обработку и алгоритм 'склейки'
повторяется. Если кол-во элементов очередной группы превышает значение
параметра *common.rrThreshold*, то группа отправляется на обработку без какой-либо
обработки.
|cft.sample.app.scheduler.workers.WorkerSimpleRR.work

|===

== Описание параметров

[cols="3", options="header"]
|===
|Название
|Описание
|Значение по умолчанию

|server.port
|Номер порта
|8081

|common.threadsNum
|Кол-во потоков в обработчике групп
|5

|common.overflowPrevType
|Тип стратегии обработки групп. Возможны значения INADVANCE и SIMPLIFIED_RR
|SIMPLIFIED_RR

|common.queueMaxSize
|Максимальное кол-во элементов в группе при работе стратегии INADVANCE
|50

|common.workingPeriod
|Интервал запуска метода для отправки групп элементов на обработку, в мс
|5000

|common.rrThreshold
|Максимальное кол-во элементов в результирующей группе при работе работе
стратении SIMPLIFIED_RR
|15

|testing.enabled
|Управляет запуском потока отправляющего тестовые данные в очередь.
Возможные значения true / false
|true

|testing.mode
|Режим генерирования тестовых данных. Может принимать значения LINEAR, RANDOM
и MANUAL
|RANDOM

|testing.pumpingPeriod
|Интервал запуска метода для генерирования тестовых данных, в мс
|100
|===

== Примеры использования

* Запуск в 10 потоков, режим обработки INADVANCE, генерация тестовых данные LINEAR:

  java -jar target/cft-sample.jar --testing.mode=LINEAR --common.threadsNum=10 --common.overflowPrevType=INADVANCE

* Запуск в 10 потоков, режим обработки INADVANCE, генерация тестовых данные RANDOM:

  java -jar target/cft-sample.jar --testing.mode=RANDOM --common.threadsNum=10 --common.overflowPrevType=INADVANCE